name: SwagLabs - Selenium Java Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Run Selenium test
        run: mvn clean compile exec:java
